</div>
<script>
    $('#content > .section').each(function(i,elem) {
        var sectionId = 'section-'+i;
        var sectionHeader = $(this).children('.header').children('h2').text();
        var navigationItem = '<li><a href="#' + sectionId + '">' + sectionHeader + '</a></li>';

        $(this).attr('id', sectionId);
        $('#left-sidebar .navigation ul').append(navigationItem);
    });

    function copytext(el) {
        var $tmp = $("<textarea>");
        $("body").append($tmp);
        $tmp.val($(el).find('textarea.code:first').val()).select();
        document.execCommand("copy");
        $tmp.remove();

        $(el).addClass('copy-success');
        setTimeout(function () {
            $(el).removeClass('copy-success');
        },400);
    }

    $('.left-sidebar .navigation li a').on( 'click', function(){
        var el = $(this);
        var dest = el.attr('href');
        if(dest !== undefined && dest !== '') {
            $('html').animate({
                    scrollTop: $(dest).offset().top
                }, 500
            );
        }
        return false;
    });
</script>
</body>
</html>