<!doctype html>
<head>
    <meta charset="utf-8">
    <title>Magento 2 debug</title>
    <meta name="description" content="Magento 2 debug">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Arvo" />
    <style>
        body
        {
            font-family: Arvo, sans-serif;

            margin: 0;

            color: #565656;
            background: #fbfaf7;
        }

        img
        {
            max-width: 100%;
        }

        .code
        {
            font-family: Monaco, 'Bitstream Vera Sans Mono', 'Lucida Console', Terminal;
            font-size: 14px;

            overflow: auto;
            overflow-y: hidden;

            width: 97%;
            padding: 12px;

            color: #00b;
            border: 1px solid #d7d8c8;
            border-radius: 4px;
            background: #f8f8f8;
        }

        .code .kd
        {
            color: #070;
        }

        .code .s2
        {
            color: #d00;
        }

        .code.copy
        {
            position: relative;

            display: inline-block;

            cursor: pointer;
        }

        .code.copy:after
        {
            font-family: Arial, sans-serif;
            font-size: 15px;
            font-weight: bolder;
            -webkit-box-align: center;
            -ms-flex-align: center;
            align-items: center;
            -webkit-box-pack: center;
            -ms-flex-pack: center;
            justify-content: center;

            background: rgb(23 23 23 / 88%);
            color: #fff;
        }

        .code.copy:hover:after
        {
            position: absolute;
            z-index: 1;
            top: 0;
            right: 0;
            width: 100%;
            height: 100%;
            content: 'Клікніть щоб скопіювати код';
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
        }

        .code.copy.copy-success:after
        {
            position: absolute;
            z-index: 1;
            top: 0;
            right: 0;
            width: 100%;
            height: 100%;
            content: '\2714';
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
            font-size: 25px;

            background: #046104c9;
        }

        code
        {
            word-spacing: -4px;
        }

        .code textarea
        {
            display: none;
        }

        h2
        {
            font-size: 25px;
            font-weight: normal;

            padding-bottom: 5px;

            border-bottom: 1px solid #ccc;
        }

        body > .container
        {
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;

            width: 100%;

            background: none;

            -webkit-box-pack: justify;
            -ms-flex-pack: justify;
            justify-content: space-between;
        }

        .left-sidebar
        {
            width: 270px;
        }

        .left-sidebar .navigation
        {
            position: fixed;

            width: 270px;
            height: 100%;
            max-height: 100vh;

            border: 1px solid #000;
            -webkit-border-top-right-radius: 4px;
            -webkit-border-bottom-right-radius: 4px;
            background-color: #171717;
        }

        .left-sidebar .navigation ul
        {
            margin: 0 0 12px;
            padding: 5px 0;

            list-style: none;
        }

        .left-sidebar .navigation ul li
        {
            padding-right: 8px;
        }

        .left-sidebar .navigation li a
        {
            font-size: 15px;
            line-height: 1.8;

            display: block;

            width: 100%;
            padding: 6px 0;
            padding-left: 12px;

            cursor: pointer;
            text-decoration: none;

            color: #fdfdfb;
        }

        .left-sidebar .navigation li a:hover
        {
            background: -o-linear-gradient(bottom, #af0011 0%, #820011 100%);
            background:    -webkit-gradient(linear, left bottom, left top, from(#af0011), to(#820011));
            background:    linear-gradient(to top, #af0011 0%, #820011 100%);
        }

        #content
        {
            width: calc(100% - 310px);
            min-height: 100vh;

            color: #232323;
        }

        #content > .section
        {
            width: 70%;
            margin: 10px 0;
            padding: 15px;

            border: 1px solid #f2f2f2;
            border-radius: 3px;
            background: #fff;
        }

        #content
        {
            line-height: 1.5rem;
        }
        .underline
        {
            text-decoration: underline;
        }

        #content ul .code{
            margin-left: -40px;
            width: calc(97% + 40px);
        }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
</head>
<body>