<!doctype html>
<head>
    <meta charset="utf-8">
    <title>Magento 2 debug</title>
    <meta name="description" content="Magento 2 debug">
    <style>
        body
        {
            font-family: Arial,'Helvetica Neue',Helvetica,sans-serif;

            color: #565656;
            background: #fafafb;
        }
        img
        {
            max-width: 100%;
        }
        .code
        {
            width: 100%;
            width: 90%;
            padding: 12px;

            color: #565656;
            border-radius: 5px;
            background: #f8f7f2;
        }
        .code.copy
        {
            position: relative;

            display: inline-block;

            cursor: pointer;
        }
        .code.copy:hover:after
        {
            font-family: Arial, sans-serif;
            font-size: 11px;

            position: absolute;
            z-index: 1;
            top: 12px;
            right: 12px;

            padding: 5px 10px;

            content: 'Копіювати код';

            border: 1px solid #e4e6e8;
            border-radius: 5px;
            background: rgba(255,255,230,.9);
        }
        code
        {
            word-spacing: -4px;
        }
        .code textarea
        {
            display: none;
        }
        h2
        {
            font-size: 1.5rem;
            font-weight: normal;
            line-height: 1.35;

            margin: 0;
            margin-bottom: 0;
        }
        body > .container
        {
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;

            width: 100%;

            background: none;

            -webkit-box-pack: justify;
            -ms-flex-pack: justify;
            justify-content: space-between;
        }
        .left-sidebar
        {
            width: 260px;

            background: #fff;
        }
        .left-sidebar .navigation
        {
            position: fixed;
            top: 8px;
            left: 8px;

            width: 240px;
            height: 100%;
            max-height: 100vh;
        }
        .left-sidebar .navigation ul
        {
            margin: 0 0 12px;
            padding: 0;

            list-style: none;
        }

        .left-sidebar .navigation li a
        {
            font-size: 15px;
            line-height: 1.8;

            display: block;

            width: 100%;
            padding: 4px;
            padding-left: 8px;

            cursor: pointer;
            text-decoration: none;

            color: #535a60;
        }
        .left-sidebar .navigation li a:hover
        {
            color: #0c0d0e;
            border-right: 3px solid #f48024;
            background: #eff0f1;
        }
        #content
        {
            width: calc(100% - 260px);
            min-height: 100vh;
            padding: 15px;

            border-left: 1px solid #8c8b8e;
        }
        #content > .section
        {
            margin-bottom: 10px;
            padding: 15px 30px;

            border: 1px solid #f2f2f2;
            border-radius: 3px;
            background: #fff;
        }
        .section .header
        {
            border-bottom: 1px solid #e4e6e8;
        }
        .underline
        {
            text-decoration: underline;
        }
    </style>
</head>
<body>