<div class="container">
    <div id="left-sidebar" class="left-sidebar">
        <div class="navigation">
            <ul>
                <li>
                    <a href="#section-1">Рекомендації</a>
                </li>
                <li>
                    <a href="#section-2">Корисні php команди для debug</a>
                </li>
                <li>
                    <a href="#section-3">Визначення версії Magento 2</a>
                </li>
                <li>
                    <a href="#section-4">Як отримати доступ до адмінки</a>
                </li>
                <li>
                    <a href="#section-5">Основні файли конфігурації</a>
                </li>
                <li>
                    <a href="#section-6">Вивід layout усієї сторінки</a>
                </li>
                <li>
                    <a href="#section-7">Вивід template path hints</a>
                </li>
                <li>
                    <a href="#section-8">Створення кастомного html темплейта для повідомлень</a>
                </li>
            </ul>
        </div>
    </div>