<?php if ($letCopy): ?>
<div class="code copy" onclick="copytext(this)">
    <code>
        <span style="color: #0000BB">
            <?= $processedСode ?>
        </span>
    </code>
    <textarea class="code"><?= trim($code); ?></textarea>
</div>
<?php else: ?>
<div class="code">
    <code>
        <span style="color: #0000BB">
            <?= $processedСode?>
        </span>
    </code>
</div>
<?php endif;?>

